name: esdc_emg
description: ESDC Emg Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^1.0.7
  google_fonts: ^2.0.0
  flutter_svg: ^0.21.0+1
  intl: ^0.17.0
  shared_preferences:
  synchronized:
  flutter_bloc: ^5.0.0
  rxdart: ^0.23.1
  fluttertoast: ^6.0.0
  http: ^0.13.0
  dio: ^4.0.0
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  overlay_support: ^1.2.1
  flutter_pdfview: ^1.0.4
  flutter_local_notifications: ^5.0.0+1
  cloud_firestore: ^1.0.7
  url_launcher: ^6.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/font/
    - asset/image/
    - asset/pdf/
    - asset/lang/

  fonts:
    - family: PopBlack
      fonts:
        - asset: asset/font/Poppins-ExtraBold.ttf
          weight: 900
        - asset: asset/font/Poppins-Bold.ttf
          weight: 800
        - asset: asset/font/Poppins-SemiBold.ttf
          weight: 700
        - asset: asset/font/Poppins-Medium.ttf
          weight: 600
        - asset: asset/font/Poppins-Regular.ttf
          weight: 500
        - asset: asset/font/Poppins-Light.ttf
          weight: 400
        - asset: asset/font/Poppins-Thin.ttf
          weight: 300
